name: Extract cloudflarewarp IPv4 from FQDNs

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:       # allows manual triggering
jobs:
  extract-ips:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Extract IPv4 addresses from FQDNs
        run: |
          # Query the A record for each FQDN and save to file
          dig +short region1.v2.argotunnel.com A > cloudflarewarp_ips
          dig +short region2.v2.argotunnel.com A >> cloudflarewarp_ips
          echo "Extracted IPv4 addresses:"
          cat cloudflarewarp_ips
          
      - name: Commit the resulting file
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add cloudflarewarp_ips
          git commit -m "Update cloudflarewarp_ips" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
