name: malwareurl_tor_v4_extract

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  extract-ipv4:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Extract IPv4 addresses
      env:
        API_KEY: ${{ secrets.MALWARE_URL_API_KEY }}
      run: |
        python - <<EOF
        import re
        import requests
        
        # Fetch data from the API
        api_url = 'https://www.malwareurl.com/reg-export-urls.php'
        params = {
            'export': 'tor',
            'key': '${{ secrets.MALWARE_URL_API_KEY }}'
        }
        
        try:
            response = requests.get(api_url, params=params)
            response.raise_for_status()
            content = response.text
            
            # Regular expression for IPv4 addresses
            ipv4_pattern = r'\b(?:[0-9]{1,3}\.){3}[0-9]{1,3}\b'
            
            # Find all IPv4 addresses and validate them
            ipv4_addresses = []
            for ip in re.finditer(ipv4_pattern, content):
                ip_addr = ip.group()
                # Validate that each octet is <= 255
                if all(0 <= int(octet) <= 255 for octet in ip_addr.split('.')):
                    ipv4_addresses.append(ip_addr)
            
            # Write unique IPv4 addresses to file
            with open('Malware_URL_v4_Processed.txt', 'w') as f:
                f.write('\n'.join(sorted(set(ipv4_addresses))))
                
        except Exception as e:
            print(f"Error occurred: {e}")
            exit(1)
        EOF
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Malware_URL_v4_Processed.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update IPv4 addresses" && git push)
