name: Update Shodan IP List

on:
  workflow_dispatch: # Manual trigger for testing

jobs:
  update_ip_list:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install DNS utilities
      - name: Install DNS Utilities
        run: sudo apt-get update && sudo apt-get install -y dnsutils

      # Debug: Show system info
      - name: Debug System Info
        run: |
          echo "Running on:"
          uname -a
          echo "DNS Utilities Version:"
          dig -v
          echo "Curl Version:"
          curl --version

      # Resolve DNS Entries and Create New IP List
      - name: Resolve DNS Entries
        run: |
          set -e  # Stop on any error
          
          # Variables
          DNS_URL="https://raw.githubusercontent.com/malindarathnayake-fts/IPLists/main/Shodan_Known_DNS"
          NEW_IP_LIST_FILE="Known_ShodanIPlist"

          # Download the DNS file
          echo "Downloading DNS entries..."
          curl -s "$DNS_URL" -o dns_entries.txt
          if [[ ! -s dns_entries.txt ]]; then
            echo "Error: DNS entries file is empty or not found."
            exit 1
          fi

          echo "DNS entries downloaded successfully:"
          cat dns_entries.txt

          # Clear previous IP list
          > resolved_ips.txt

          # Resolve DNS entries to IPs
          echo "Resolving DNS entries to IPs..."
          while read -r dns; do
            if [[ -n "$dns" ]]; then
              echo "Resolving $dns..."
              ips=$(dig +short "$dns" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
              if [[ -n "$ips" ]]; then
                echo "$ips" >> resolved_ips.txt
              else
                echo "Warning: Unable to resolve $dns"
              fi
            fi
          done < dns_entries.txt

          # Check if any IPs were resolved
          if [[ ! -s resolved_ips.txt ]]; then
            echo "Warning: No IPs resolved. Exiting without creating a new IP list."
            exit 0
          fi

          echo "Resolved IPs:"
          cat resolved_ips.txt

          # Sort and remove duplicates
          sort -u resolved_ips.txt -o resolved_ips.txt
          echo "Sorted and deduplicated IPs:"
          cat resolved_ips.txt

          # Write to a new IP list file
          echo "Creating a new IP list file..."
          mv resolved_ips.txt "$NEW_IP_LIST_FILE"
          echo "New IP list file created: $NEW_IP_LIST_FILE"

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add Known_ShodanIPlist
          git commit -m "Updated Known_ShodanIPlist from DNS entries"
          git push
