name: Update Shodan IP List

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_ip_list:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Resolve DNS entries and update IP list
      - name: Resolve DNS Entries and Update IP List
        run: |
          # Set the URLs for DNS and IP list files
          DNS_URL="https://raw.githubusercontent.com/malindarathnayake-fts/IPLists/main/Shodan_Known_DNS"
          IP_LIST_FILE="Shodan_IPlist"

          # Download the DNS file
          curl -s $DNS_URL -o dns_entries.txt

          # Resolve DNS entries to IPs
          > resolved_ips.txt # Clear the file before adding new entries
          while read -r dns; do
            if [[ -n "$dns" ]]; then
              ips=$(dig +short $dns | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
              if [[ -n "$ips" ]]; then
                echo "$ips" >> resolved_ips.txt
              fi
            fi
          done < dns_entries.txt

          # Sort and remove duplicates
          sort -u resolved_ips.txt -o resolved_ips.txt

          # Update the IP list in the repository
          mv resolved_ips.txt $IP_LIST_FILE

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add $IP_LIST_FILE
          git commit -m "Updated Shodan IP List from DNS entries"
          git push
