name: Update Shodan IP List

on:
  schedule:
    - cron: '0 2 * * *' # Runs daily at 2 AM UTC
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update_ip_list:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install DNS utilities
      - name: Install DNS Utilities
        run: sudo apt-get update && sudo apt-get install -y dnsutils

      # Resolve DNS Entries and Update IP List
      - name: Resolve DNS Entries and Update IP List
        run: |
          # Set the URLs for DNS and IP list files
          DNS_URL="https://raw.githubusercontent.com/malindarathnayake-fts/IPLists/main/Shodan_Known_DNS"
          IP_LIST_FILE="Shodan_IPlist"

          # Check if `dig` is installed
          if ! command -v dig &>/dev/null; then
            echo "Error: 'dig' command not found. Please install 'dnsutils'."
            exit 1
          fi

          # Download the DNS file
          curl -s "$DNS_URL" -o dns_entries.txt
          if [[ $? -ne 0 ]]; then
            echo "Error: Failed to download DNS entries file."
            exit 1
          fi

          # Check if DNS entries file is empty
          if [[ ! -s dns_entries.txt ]]; then
            echo "Error: DNS entries file is empty or not found."
            exit 1
          fi

          # Clear previous IP list before adding new entries
          > resolved_ips.txt

          # Resolve DNS entries to IPs
          echo "Resolving DNS entries..."
          while read -r dns; do
            if [[ -n "$dns" ]]; then
              # Use dig to resolve DNS to IPs
              ips=$(dig +short "$dns" | grep -Eo '([0-9]{1,3}\.){3}[0-9]{1,3}')
              if [[ -n "$ips" ]]; then
                echo "$ips" >> resolved_ips.txt
              else
                echo "Warning: Unable to resolve $dns" >&2
              fi
            fi
          done < dns_entries.txt

          # Check if resolved_ips.txt has content
          if [[ ! -s resolved_ips.txt ]]; then
            echo "Warning: No valid IPs resolved. Skipping update."
            exit 0
          fi

          # Sort and remove duplicates
          sort -u resolved_ips.txt -o resolved_ips.txt

          # Update the IP list in the repository
          touch "$IP_LIST_FILE"
          mv resolved_ips.txt "$IP_LIST_FILE"

          echo "DNS resolution completed. IP list updated successfully."

      # Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add Shodan_IPlist
          git commit -m "Updated Shodan IP List from DNS entries"
          git push
